name: aquasense
description: "Smart Water Supply and Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  sensors_plus: ^5.0.1

  # Latest stable Firebase packages (modern, compatible set)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_app_check: ^0.4.0+1
  cloud_functions: ^6.0.1

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Social Login & Security
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3

  # Utility & Payments
  dropdown_search: ^5.0.6
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  path: ^1.9.0
  fl_chart: ^0.68.0
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.3.6
  rxdart: ^0.27.7

  # ✅ PDF Generation & Sharing
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  share_plus: ^11.1.0
  file_picker: ^8.0.5
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^31.1.17

  # ✅ Fixed fluttertoast (latest valid version)
  fluttertoast: ^8.2.12

  # ✅ Machine Learning
  ml_algo: ^16.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"