// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhMFCOb6g5KIDsU28HOXw6BwBe48TJ3c',
    appId: '1:575158481229:web:06e1f8bfbf680d96e10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    authDomain: 'aquasense-e6f48.firebaseapp.com',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
    measurementId: 'G-NHPXZ1J5E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtz0CSuqcO52DULMGLq3dRw1zF5l6s7rs',
    appId: '1:575158481229:android:45382e4e1a403269e10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVg_qJLUbXzCkHZzBzq6dPHEc_ctDuV0',
    appId: '1:575158481229:ios:14bb89f0247ec4dde10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
    androidClientId: '575158481229-08hkdk4k40nkvm90ql6mir5bfipb0454c.apps.googleusercontent.com',
    iosClientId: '575158481229-6ag09ab2ojng9niap60b8vrno04tc0mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasense',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhMFCOb6g5KIDsU28HOXw6BwBe48TJ3c',
    appId: '1:575158481229:web:8fbe346ce7354538e10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    authDomain: 'aquasense-e6f48.firebaseapp.com',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
    measurementId: 'G-VSK3BPZL0W',
  );

  // ✅ Custom property for Google Sign-In (Web only)
  static const String webClientId =
      '575158481229-1c4g51hrtnfg2imp83u608ur2sdn6n37.apps.googleusercontent.com';
}